EXPERIMENT 2 | JEGO MARCO E. GODOY | 2ECE-A

NORMALIZATION PROBLEM

In [5]:
import numpy as np

In [4]:
#Generate 5x5 array with random numbers
x = np.random.random([5,5])

#Getting the mean and standard deviation of the array
y = x.mean()
z = x.std()

#normalized x
normx = (x-y)/z
print(normx)

[[-0.34229424  0.57639036 -0.9755033   1.01445586 -1.02345348]
 [ 0.88058162  0.99051101 -0.93278058  0.16946968  0.18351819]
 [ 1.04650645  1.9835006   1.0991913  -1.08500802  0.09467688]
 [-0.9943937   0.59340783 -1.54494164 -1.50859446 -0.66526793]
 [-1.25840337  1.28237277 -0.58222662 -0.17091874  1.16920351]]


DIVISIBLE BY 3 PROBLEM

In [8]:
# Generate the 10x10 array with the square of the first 100 pos integers
d = np.arange(1,101).reshape(10,10)**2
# Find all elements divisible by 3
by3 = d[d % 3 == 0].reshape(3,11)

# Print the 10x10 array and the elements divisble by 3
print("Array of squares: \n", d)
print("\nElements divisible by 3: \n", by3)

Array of squares: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]


THANK YOU!